@startuml キャンペーン
actor 宿泊客#DDDDDD;line:black;line.bold;
 rectangle ホテル宿泊予約{
    usecase キャンペーン
    usecase (<u>予約</u>\n拡張点\nキャンペーン価格) as input
    usecase  ログイン
 }
    input <. キャンペーン: <<extend>>
    宿泊客 --> input
    ログイン<.input : << include >>
@enduml