@startuml 資格取得のオブジェクト図

object "<u>社員1:社員</u>" as e1{
    氏名 = 高橋洋平さん
}

object "<u>社員2:社員</u>" as e2{
    氏名 = 樋口正之さん
}

object "<u>資格1:資格</u>" as l1{
    名称 = Linuc試験Level1
}

object "<u>資格2:資格</u>" as l2{
    名称 = 情報処理安全確保支援士
}

e1 -- l1:持つ
e2 -- l1:持つ
e1 -- l2:持つ
@enduml